# Generated by Django 4.2.5 on 2023-09-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.TextField(max_length=40)),
                ('old_url', models.TextField()),
                ('ip', models.TextField()),
                ('date', models.IntegerField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.TextField(max_length=40)),
                ('ip', models.TextField()),
            ],
        ),
    ]
